backtest:
  start_time: "2017-01-01"
  end_time: "2020-08-01"
  account: 100000000
  benchmark: CSI300_BENCH
  exchange_kwargs:
    freq: "day"
    limit_threshold: 0.095
    deal_price: "close"
    open_cost: 0.0005
    close_cost: 0.0015
    min_cost: 5